# 


name: AWS Lab 2 Grading
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  grade-lab2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest boto3 requests botocore
          
             
      - name: Configure AWS credentials via OICD
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/github_aprudencio_role
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy --template-file cloudformation/lab2.yml --stack-name coderoad-lab-2  --no-fail-on-empty-changeset 
     
      - name: Run pytest tests
        run: |
          pytest test_lab2.py  

      #- name: Cleanup - Delete CloudFormation Stack
      #  run: |
      #    aws cloudformation delete-stack --stack-name coderoad-lab-2